require('dotenv').config()
import { checkEnvVar } from './utilts'

const {
    REDDIT_CLIENT_ID,
    REDDIT_CLIENT_SECRET,
    REDDIT_ACCESS_TOKEN,
    REDDIT_REFRESH_TOKEN,
    SUBREDDIT_NAME,
    ETH_RPC_URL,
    ETH_ACCOUNT_PRIVKEY,
    ETH_EVENTS_FROMBLOCK
} = process.env

checkEnvVar(REDDIT_CLIENT_ID,     'REDDIT_CLIENT_ID')
checkEnvVar(REDDIT_CLIENT_SECRET, 'REDDIT_CLIENT_SECRET')
checkEnvVar(REDDIT_ACCESS_TOKEN,  'REDDIT_ACCESS_TOKEN')
checkEnvVar(REDDIT_REFRESH_TOKEN, 'REDDIT_REFRESH_TOKEN')
checkEnvVar(SUBREDDIT_NAME,       'SUBREDDIT_NAME')
checkEnvVar(ETH_RPC_URL,          'ETH_RPC_URL')
checkEnvVar(ETH_RPC_URL,          'ETH_ACCOUNT_PRIVKEY')
checkEnvVar(ETH_EVENTS_FROMBLOCK, 'ETH_EVENTS_FROMBLOCK')

export {
    REDDIT_CLIENT_ID,
    REDDIT_CLIENT_SECRET,
    REDDIT_ACCESS_TOKEN,
    REDDIT_REFRESH_TOKEN,
    SUBREDDIT_NAME,
    ETH_RPC_URL,
    ETH_ACCOUNT_PRIVKEY,
    ETH_EVENTS_FROMBLOCK
}

export const VERSION = '0.1.0'
export const USER_AGENT = `User-Agent: node:eth.curatem.automoderator:v${VERSION} (built by /u/liamzebedee)`

export const POLL_NEW_POSTS_INTERVAL = 1000 * 30